In [1]:
import numpy as np

# Given list
Lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Convert list to numpy array
array = np.array(Lst)

# Replace odd elements with -2
array[array % 2 != 0] = -2

print(array)


[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


In [2]:
import numpy as np

# Given array
arr = [1, 2, 3, 4, 5, 8, 9, 10, 12, 22, 32, 54, 99, 6, 7]

# Convert to numpy array
arr = np.array(arr)

# Find elements between 8 and 15
result = arr[(arr >= 8) & (arr <= 15)]

print(result)


[ 8  9 10 12]


In [3]:
import numpy as np

# Create a 3x3 array with numbers from 1 to 9
array = np.arange(1, 10).reshape(3, 3)

# Swap columns 1 and 2
array[:, [0, 1]] = array[:, [1, 0]]

print(array)


[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [4]:
import numpy as np

# Given array
arr = np.array([[1.3, 2.5, 3.6, np.nan],
                [2.6, 3.3, np.nan, 5.5],
                [2.1, 3.2, 5.4, 6.5]])

# Calculate the column-wise mean, ignoring NaN values
col_mean = np.nanmean(arr, axis=0)

# Find indices where NaN values are present
inds = np.where(np.isnan(arr))

# Replace NaN values with the corresponding mean of the column
arr[inds] = np.take(col_mean, inds[1])

print(arr)


[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [6]:
import numpy as np

# Given array
arr = np.array([[2, 4, 6], [1, 3, 5]])

# Convert array to matrix
matrix = np.matrix(arr)
print("Matrix:\n", matrix)
# Sort the matrix
sorted_matrix = np.sort(matrix, axis=None).reshape(matrix.shape)
print("Sorted Matrix:\n", sorted_matrix)


Matrix:
 [[2 4 6]
 [1 3 5]]
Sorted Matrix:
 [[1 2 3]
 [4 5 6]]
